### ISSUE TITLE
Failed to download dist package from composer for version 1.5.4, which is dependency of lazyrecord

### ISSUE THREAD

**Issue by Ronmi** [c9s/ConfigKit#3]
Got messge bwlow when running `composer.phar install`, then it fallback to download from source with `git clone --no-checkout 'git@github.com:c9s/php-ConfigKit.git'` , which is not acceptable in my case (running in custom CI env, cant login to github)

```
  - Installing corneltek/configkit (1.5.4)
    Downloading: Connecting...    Failed to download corneltek/configkit from dist: The "https://api.github.com/repos/c9s/php-ConfigKit/zipball/c17cab1e0f8861b7b8688c0c43ae2a4e2e63ac32" file could not be downloaded (HTTP/1.1 404 Not Found)
```

I guess it's because the project was renamed once after registered on packagist.org?

**Comment by c9s** [comment]
I think it's caused by packagist (or GitHub)

**Comment by Ronmi** [comment]
Can be temporarily resolveed by adding custom repository in composer.json, which is dirty as my code XD
```json
  "repositories": [{
    "type": "vcs",
    "url": "https://github.com/c9s/ConfigKit.git"
  }]
```

**Comment by c9s** [comment]
sometimes packagist doesn't work, does it work for you now?

**Comment by Ronmi** [comment]
no, same problem

```sh
- Installing corneltek/configkit (1.5.4)

  Downloading: Connecting...    Failed to download corneltek/configkit from dist: The "https://api.github.com/repos/c9s/php-ConfigKit/zipball/c17cab1e0f8861b7b8688c0c43ae2a4e2e63ac32" file could not be downloaded (HTTP/1.1 404 Not Found)
  Now trying to download from source
- Installing corneltek/configkit (1.5.4)
  Cloning c17cab1e0f8861b7b8688c0c43ae2a4e2e63ac32
```

**Comment by c9s** [comment]
I just shipped 1.5.5, see if github works for you?

**Comment by c9s** [comment]
I guess the sha1 is rewritten so the dist file couldn't be found.

**Comment by Ronmi** [comment]
It's totally fixed now! I guess you're right >_^
